const fs = require('node:fs');
const path = require('node:path');
const readline = require('node:readline');

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});

const ask = (question) => new Promise((resolve) => rl.question(question, resolve));

async function run() {
  console.log('\n========================================');
  console.log('🚀 GradSync Production Setup Wizard 🚀');
  console.log('========================================\n');

  console.log('This wizard will generate your .env file for production.\n');

  const mongoUri = await ask('1. Enter your MongoDB Atlas Connection String:\n   (e.g., mongodb+srv://user:pass@cluster.mongodb.net/gradsync)\n   > ');

  const rcloneRemote = await ask('\n2. Enter your RClone remote drive name:\n   (Press Enter to default to "drive:")\n   > ');

  const isDryRun = await ask('\n3. Should RClone run in dry-run mode to prevent actual uploads? (y/n)\n   > ');

  const port = await ask('\n4. What port should the server run on? (Default: 8787)\n   > ');

  const envContent = `# Auto-generated by setup.cjs
MONGO_URI=${mongoUri || 'mongodb://127.0.0.1:27017/gradsync'}
GRADSYNC_RCLONE_REMOTE=${rcloneRemote || 'drive:'}
GRADSYNC_RCLONE_DRY_RUN=${isDryRun.toLowerCase() === 'y' ? 'true' : 'false'}
PORT=${port || '8787'}
`;

  const envPath = path.join(__dirname, '..', '.env');
  fs.writeFileSync(envPath, envContent);

  console.log('\n========================================');
  console.log('✅ Success! Your .env file has been created.');
  console.log('You can now run "npm run local" to start the app.');
  console.log('========================================\n');

  rl.close();
}

run();
